---
# Copy default files tasks for fedora

- name: Copy default files
  shell: >-
      rm "{{ '/etc/pam.d/'
         + login_defs_stat_pam_auth_result_item.login_defs_pam_auth_file }}";
      cp "{{ '/etc/authselect/'
         + login_defs_stat_pam_auth_result_item.login_defs_pam_auth_file }}" "{{ '/etc/pam.d/'
         + login_defs_stat_pam_auth_result_item.login_defs_pam_auth_file }}"
  when:
        - login_defs_stat_pam_auth_result_item.stat.islnk is defined
        - login_defs_stat_pam_auth_result_item.stat.islnk
  loop: "{{ login_defs_stat_pam_auth_result.results }}"
  loop_control:
    loop_var: login_defs_stat_pam_auth_result_item
  args:
    warn: no
