---
# Copy default files tasks for CentOS/RHEL

- name: Copy default files
  copy:
    src: >-
      {{ "/etc/pam.d/"
         + login_defs_stat_pam_auth_result_item.login_defs_pam_auth_file
         + "-ac" }}
    dest: >-
      {{ "/etc/pam.d/"
         + login_defs_stat_pam_auth_result_item.login_defs_pam_auth_file }}
    remote_src: yes
  when:
    - login_defs_stat_pam_auth_result_item.stat.islnk is defined
    - login_defs_stat_pam_auth_result_item.stat.islnk
    - ansible_facts.distribution | lower in ["centos". "redhat"]
  loop: "{{ login_defs_stat_pam_auth_result.results }}"
  loop_control:
    loop_var: login_defs_stat_pam_auth_result_item
