# centos7-setup.yml
# configure passsword requiremnts

- name: Check system-auth EOF configuration
  lineinfile:
    path: /etc/pam.d/system-auth
    state: present
    insertbefore: BOF
    line: "password requisite pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-0"

- name: Check system-auth BOF configuration
  lineinfile:
    path: /etc/pam.d/system-auth
    state: present
    insertafter: EOF
    line: "password sufficient pam_unix.so sha512 shadow nullok try_first_pass use_authtok remember=5"
