---
# Cracklib tasks

- name: Setup password cracklib module for system-auth
  lineinfile:
    path: "{{ login_defs_system_auth_config_file }}"
    state: present
    regexp: "^password( +)requisite( +)pam_cracklib.so"
    line: "password\\1requisite\\2{{ login_defs_cracklib_pam_d_config }}"
    backrefs: yes
  when: ansible_facts.distribution_major_version is version("6", "<=")
  tags:
    - role::login_defs::cracklib
