---

- name: Setup login defs
  block:
    - ansible.builtin.include_tasks: faillock.yml
      when: ansible_facts.distribution_major_version is version("7", ">=")

    - ansible.builtin.include_tasks: login_defs.yml
    - ansible.builtin.include_tasks: cracklib.yml
    - ansible.builtin.include_tasks: pwquality.yml
    - ansible.builtin.include_tasks: unix.yml
  tags:
    - role::login_defs
