---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- block:
    - name: setup login.defs file
      template:
        backup: yes
        src: login_defs.j2
        dest: "{{ login_defs_config_file }}"
        owner: root
        group: root
        mode: 0644

    - name: setup password cracklib module for system-auth
      lineinfile:
        path: "{{ login_defs_system_auth_config_file }}"
        state: present
        regexp: "^password( +)requisite( +)"
        line: "password\\1requisite\\2{{ login_defs_cracklib_pam_d_config }}"
        backrefs: yes
      when: ansible_facts.distribution_major_version is version("6", "<=")

    - name: setup password pwquality module for system-auth
      lineinfile:
        path: "{{ login_defs_system_auth_config_file }}"
        state: present
        regexp: "^password( +)requisite( +)"
        backrefs: yes
        line: "password\\1requisite\\2{{ login_defs_pwquality_pam_d_config }}"
      when: ansible_facts.distribution_major_version is version("7", ">=")

    - name: setup password unix module for system-auth
      lineinfile:
        path: "{{ login_defs_system_auth_config_file }}"
        state: present
        regexp: "^password( +)sufficient( +)"
        backrefs: yes
        line: "password\\1sufficient\\2{{ login_defs_pam_unix_pam_d_config }}"
  tags:
    - role::login_defs
