---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- block:
    - include_tasks: authconfig.yml
    - include_tasks: faillock.yml
    - include_tasks: login_defs.yml
    - include_tasks: cracklib.yml
    - include_tasks: pwquality.yml
    - include_tasks: unix.yml
  tags:
    - role::login_defs
