---
# Role tasks
- name: Configure login.defs file
  template:
    backup: yes
    src: login_defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- include: centos6-system-auth.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '7'

- include: centos7-system-auth.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

  tags:
    - role::login_defs
