---

- name: Setup password pwquality module for system-auth
  ansible.builtin.lineinfile:
    path: "{{ login_defs_system_auth_config_file }}"
    state: present
    regexp: "^password( +)requisite( +)pam_pwquality.so"
    line: "password\\1requisite\\2{{ login_defs_pwquality_pam_d_config }}"
    backrefs: yes
  when: ansible_facts.distribution_major_version is version("7", ">=")
  tags:
    - role::login_defs::pwquality
