---
# Password unix module tasks

- name: Setup password unix module for system-auth
  lineinfile:
    path: "{{ login_defs_system_auth_config_file }}"
    state: present
    regexp: "^password( +)sufficient( +)pam_unix.so"
    line: "password\\1sufficient\\2{{ login_defs_pam_unix_pam_d_config }}"
    backrefs: yes
  tags:
    - role::login_defs::unix
