---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    box: centos/6
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          login_defs_login_retries: 3
          login_defs_create_home: yes
          login_defs_default_home: no
          login_defs_display_last_login: yes
          login_defs_log_ok_logins: yes
          login_defs_log_unknown_fail_usernames: yes
          login_defs_login_timeout: 300
          login_defs_default_new_file_permissions: "0027"
          login_defs_password_maximum_days: 120
          login_defs_password_minimum_days: 0
          login_defs_password_minimum_length: 8
          login_defs_password_warning_age: 7
          login_defs_password_always_warn: yes
          login_defs_password_change_tries: 5
          login_defs_password_remember: 5
          login_defs_password_type: ""
          login_defs_password_ucredit: -1
          login_defs_password_lcredit: -1
          login_defs_password_dcredit: -1
          login_defs_password_ocredit: -0
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
