---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    box: centos/6
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/8
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          login_defs_login_retries: 3
          login_defs_create_home: yes
          login_defs_default_home: no
          login_defs_display_last_login: yes
          login_defs_log_ok_logins: yes
          login_defs_log_unknown_fail_usernames: yes
          login_defs_login_timeout: 300
          login_defs_default_new_file_permissions: "0027"
          login_defs_password_maximum_days: 120
          login_defs_password_minimum_days: 0
          login_defs_password_minimum_length: 8
          login_defs_password_warning_age: 7
          login_defs_password_always_warn: yes
          login_defs_password_change_tries: 5
          login_defs_password_remember: 5
          login_defs_password_type: ""
          login_defs_password_ucredit: -1
          login_defs_password_lcredit: -1
          login_defs_password_dcredit: -1
          login_defs_password_ocredit: -0
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
