---

- name: Prepare CentOS 6 hosts
  hosts: molecule_hosts_centos_6
  gather_facts: no
  become: yes
  tasks:
    - name: Disable repos mirror list
      replace:
        path: "/etc/yum.repos.d/{{ repo_file }}"
        regexp: "(^mirrorlist=.*)"
        replace: "#\\1"
      loop: "{{ repo_files }}"
      loop_control:
        loop_var: repo_file

    - name: Point repos to vault
      replace:
        path: "/etc/yum.repos.d/{{ repo_file }}"
        regexp: "#baseurl=http://mirror.centos.org/"
        replace: "baseurl=http://vault.centos.org/"
      loop: "{{ repo_files }}"
      loop_control:
        loop_var: repo_file
  vars:
    repo_files:
      - CentOS-Base.repo
      - CentOS-Debuginfo.repo
      - CentOS-fasttrack.repo

- name: Prepare
  hosts: molecule_hosts_centos_7
  gather_facts: no
  become: yes
  tasks:
    - name: Install required packages
      package:
        name: libselinux-python
        state: present
